### ISSUE TITLE
Error preventing server to start with Minetest 5.2

### ISSUE THREAD

**Issue by Shazen** [Sokomine/handle_schematics#12]
Hi, 
Since update Minetest 5.2 i encounter an error preventing server to start :+1: 
```
ERROR[Main]: ModError: Failed to load and run script from minetest/mods/handle_schematics/init.lua:
ERROR[Main]: Unknown node: stairs:stair_pine_wood
ERROR[Main]: stack traceback:
ERROR[Main]: [C]: in function 'get_content_id'
ERROR[Main]: minetest/mods/handle_schematics/replacements_global.lua:128: in function 'set_node_is_ground'
ERROR[Main]: minetest/mods/handle_schematics/replacements_wood.lua:153: in function 'add_material'
ERROR[Main]: minetest/mods/handle_schematics/replacements_wood.lua:194: in function 'construct_wood_type_list'
ERROR[Main]: minetest/mods/handle_schematics/replacements_wood.lua:293: in main chunk
ERROR[Main]: [C]: in function 'dofile'
ERROR[Main]: minetest/mods/handle_schematics/init.lua:101: in main chunk
```
Any idea how to patch this ?
regards,
Sha

**Comment by top4ek** [comment]
Same for me :(

**Comment by daytonnvpaul** [comment]
Similar, with different error messages.

`
2020-05-27 03:06:10: ERROR[Main]: stack traceback:
2020-05-27 03:06:10: ERROR[Main]:       [C]: in function 'get_content_id'
2020-05-27 03:06:10: ERROR[Main]:       ...in/../mods/handle_schematics/dirt_is_
not_always_dirt.lua:16: in function 'add_also_acceptable'
2020-05-27 03:06:10: ERROR[Main]:       ...in/../mods/handle_schematics/dirt_is_
not_always_dirt.lua:82: in function 'enable_doors_open_closed'
2020-05-27 03:06:10: ERROR[Main]:       ...ommy/LW5/minetest/bin/../mods/handle_
schematics/init.lua:126: in main chunk`

**Comment by olea** [comment]
My report is related with moretrees mod:

```
2020-06-16 22:08:17: ERROR[Main]: ModError: Failed to load and run script from /home/minetest/.minetest/mods/handle_schematics/init.lua:
2020-06-16 22:08:17: ERROR[Main]: Unknown node: moretrees:jungletree_sapling
2020-06-16 22:08:17: ERROR[Main]: stack traceback:
2020-06-16 22:08:17: ERROR[Main]: 	[C]: in function 'get_content_id'
2020-06-16 22:08:17: ERROR[Main]: 	...etest/mods/handle_schematics/dirt_is_not_always_dirt.lua:16: in function 'add_also_acceptable'
2020-06-16 22:08:17: ERROR[Main]: 	...etest/mods/handle_schematics/dirt_is_not_always_dirt.lua:82: in function 'enable_doors_open_closed'
2020-06-16 22:08:17: ERROR[Main]: 	/home/minetest/.minetest/mods/handle_schematics/init.lua:126: in main chunk
```

**Comment by SmallJoker** [comment]
@Shazen This is likely fixed by 5a3b8b548fd5 or Minetest 5.3.0-dev (engine issue).
@daytonnvpaul This issue is either fixed in 659d04965f or Minetest 5.3.0-dev (engine issue).
@olea How can I reproduce this issue? Which mods need to be enabled?
  -> also likely fixed in Minetest 5.3.0-dev (engine issue).

**Comment by HeyITGuyFixIt** [comment]
@SmallJoker I am experiencing the same error @Shazen is experiencing. I am using the latest version of this mod, which includes the commit you mentioned and am still seeing the error.

**Comment by HeyITGuyFixIt** [comment]
I think I found a fix for this issue. I will work on a pull request that addresses it.

**Comment by SmallJoker** [comment]
@HeyITGuyFixIt Did Minetest 5.3.0 fix your issue? If not, please check whether the error is different to the report above. If that's the case, it might be better to open a new issue.
In case the issue still persists, I might look into this sometime in case Sokomine is busy.

**Comment by HybridDog** [comment]
https://github.com/minetest/minetest/pull/9458#issuecomment-600255726

**Comment by Sokomine** [comment]
I've added error handling for this in the meantime. Sorry that it took so long! Please test the newest version.
